# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.normalized_constant <- function(norm, degree, theta, f, offset_tk, offset) {
    .Call('PAFit_normalized_constant', PACKAGE = 'PAFit', norm, degree, theta, f, offset_tk, offset)
}

.normalized_constant_alpha <- function(norm, alpha, PA_offset, degree, theta, f, offset_tk, offset) {
    .Call('PAFit_normalized_constant_alpha', PACKAGE = 'PAFit', norm, alpha, PA_offset, degree, theta, f, offset_tk, offset)
}

.get_stats <- function(time_stamp, unique_stamp, in_node, out_node, all_node, ok_node, bin_vector, max_node_id, undirected, only_PA, time_vector, Sum_m_k, n_tk, m_tk, m_t, offset_tk, z_j, node_degree, offset_m_tk, only_true_deg) {
    .Call('PAFit_get_stats', PACKAGE = 'PAFit', time_stamp, unique_stamp, in_node, out_node, all_node, ok_node, bin_vector, max_node_id, undirected, only_PA, time_vector, Sum_m_k, n_tk, m_tk, m_t, offset_tk, z_j, node_degree, offset_m_tk, only_true_deg)
}

.update_f <- function(f, non_zero_f, degree, theta, z_j, normalized_const, m_t, shape, rate, offset) {
    .Call('PAFit_update_f', PACKAGE = 'PAFit', f, non_zero_f, degree, theta, z_j, normalized_const, m_t, shape, rate, offset)
}

.update_offset <- function(offset_n_tk, offset_m_tk, theta, normalized_const, m_t, shape, rate) {
    .Call('PAFit_update_offset', PACKAGE = 'PAFit', offset_n_tk, offset_m_tk, theta, normalized_const, m_t, shape, rate)
}

.update_f_alpha <- function(f, non_zero_f, alpha, PA_offset, degree, theta, z_j, normalized_const, m_t, shape, rate) {
    .Call('PAFit_update_f_alpha', PACKAGE = 'PAFit', f, non_zero_f, alpha, PA_offset, degree, theta, z_j, normalized_const, m_t, shape, rate)
}

.update_alpha <- function(non_zero_theta, norm, f, PA_offset, theta, degree, m_t, Sum_m_k, offset_tk, offset) {
    .Call('PAFit_update_alpha', PACKAGE = 'PAFit', non_zero_theta, norm, f, PA_offset, theta, degree, m_t, Sum_m_k, offset_tk, offset)
}

.var_alpha <- function(alpha, non_zero_theta, norm, f, PA_offset, theta, degree, m_t, Sum_m_k, offset_tk, offset) {
    .Call('PAFit_var_alpha', PACKAGE = 'PAFit', alpha, non_zero_theta, norm, f, PA_offset, theta, degree, m_t, Sum_m_k, offset_tk, offset)
}

.coeff_theta <- function(degree, f, normalized_const, m_t, length_theta) {
    .Call('PAFit_coeff_theta', PACKAGE = 'PAFit', degree, f, normalized_const, m_t, length_theta)
}

.coeff_var <- function(degree, f, normalized_const, m_t, offset, length_theta) {
    .Call('PAFit_coeff_var', PACKAGE = 'PAFit', degree, f, normalized_const, m_t, offset, length_theta)
}

.cal_var_f <- function(cov_f, non_zero_f, degree, theta, f, z_j, normalized_const, m_t, shape) {
    .Call('PAFit_cal_var_f', PACKAGE = 'PAFit', cov_f, non_zero_f, degree, theta, f, z_j, normalized_const, m_t, shape)
}

